### ISSUE TITLE
Production Tool Update

### ISSUE THREAD

**Issue by taylor-an** [WIZnet-WizFi360/Release#2]
Production Tool Update

Let me know when you completed

**Comment by IssacWangWiznet** [comment]
hi, everyone, i see the firmware in github may not be the lastest version, i may advice you can refer to [http://www.winnermicro.com/upload/1/editor/1551775085307.zip](url)
this is the lastest version 3.02.00
and the presentation page is [http://www.winnermicro.com/html/1/156/158/497.html](url)
@taylor-an

**Comment by taylor-an** [comment]
Moved this issue.
