### ISSUE TITLE
[WizFi Upgrade Tool]Remove Encryption

### ISSUE THREAD

**Issue by taylor-an** [WIZnet-WizFi360/Release#3]

**Comment by IssacWangWiznet** [comment]
hi taylor-an, may i ask a question? i want to konw what's the name you want for user version and internal version of WizFi Upgrade Tool

**Comment by IssacWangWiznet** [comment]
hi taylor, i have sent WizFi Upgrade Tool user version to you on QQ, you can check it ,
i made some changes

1.remove encryption
2.remove device select(no need anymore)
3.remove check module first 20 bytes from uart0(no need anymore)
4.just can select .img file
5.remove erase flash checkbox

and this version just can download img file ,so you may just can update module with _GZ.img or _SEC.img

**Comment by taylor-an** [comment]
Hi Issac,

I uploaded instead of you. 0c1fffa7e4a7c4ac05d9ff488e90326d14d13b1a
and I think that you may make a decision of WizFi Upgrade Tool version.
I will inform if it needs.

Thank you.

**Comment by taylor-an** [comment]
Moved this issue.
