### ISSUE TITLE
[WizFi Upgrade Tool]Need to add AT Command to uart0

### ISSUE THREAD

**Issue by AisekuOu** [WIZnet-WizFi360/Release#7]
[WizFi Upgrade Tool]Need to add AT Command to uart0

As we know, we now use uart0 for ISP Download, and uart1 for AT Command.
Since we need to read mac address from module before we erase flash and dlownload firmware, 
that mean we need to process AT Command and ISP Download in uart0,
so we may need to add 

AT+RESTORE
AT+CIPAPMAC_CUR?
AT+CIPSTAMAC_CUR?
AT+CIPAPMAC_DEF=xxx.xxx.xx.x
AT+CIPSTAMAC_DEF=xxx.xxx.xx.x

to uart0

**Comment by taylor-an** [comment]
Moved this issue.
